# server config
server:
  port: 8001
  servlet:
    session:
      timeout: 360000s
spring:
  profiles:
    active: dev, local
# 운영환경 or 로컬 환경 중에 선택하세요.
#    active: prod
  config:
    activate:
      on-profile: develop
    use-legacy-processing: true

# jpa config
  jpa:
    generate-ddl : true
#    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: create

    web:
      resources:
        static-locations: file:src/main/resources/static/

  # file upload
  servlet:
    multipart:
      # 파일 업로드 가능 여부 선택
      enabled: true
      # 업로드된 파일의 임시 저장 경로
#      location: C:\
      # 한 번에 최대 업로드 가능 용량
      max-request-size: 100MB
      # 파일 하나의 최대 크기
      max-file-size: 20MB


